[build]
  publish = "docs/export/"
  command = "pnpm docs:build"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "./packages/netlify-plugin-cache-docs"

[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[plugins]]
  package = "netlify-plugin-brotli"
